### ISSUE TITLE
Show Invited Polls in the Dashboard

### ISSUE THREAD

**Issue by aniketbiswas21** [AnandBaburajan/Kukkee#115]
**Is your feature request related to a problem? Please describe.**
We can show the polls that a user has been invited to vote, but hasn't voted yet. This can be a very beneficial feature if a user logs in to the dashboard and is able to see the polls in which he is supposed to vote. This can also be extended as a way to see the ongoing poll count status of the meeting.

**Describe the solution you'd like**
We can create another section for invited polls.

**Describe alternatives you've considered**
Currently, I cannot see any other alternatives. In the current iteration,  a user has to go through their emails to see all the invited polls.

**Additional context**
I would like to work on this issue. I will be creating another issue on the RocketMeet-Server for the API implementation.

Server-side issue: RocketMeet/RocketMeet-client#147

**Comment by AnandBaburajan** [comment]
Thanks! This is a nice-to-have feature, but from the discussions at https://github.com/RocketMeet/RocketMeet-client/issues/106 and at our Gitter chatroom, we need to really think and discuss about new features since we're thinking about some major changes to our product. We would appreciate it if you could join the discussion and let us know what you think!

**Comment by aniketbiswas21** [comment]
Sure! Would love to

**Comment by AnandBaburajan** [comment]
Updates: we don't have the feature to invite participants as of now but let's leave this issue open because we might, soon.

**Comment by AnandBaburajan** [comment]
Closing since we want to keep Kukkee as simple as possible.
